/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpproject;

import Classes.Log;
import java.awt.Color;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    public String un = "";
    public java.util.Date logIn = null;
    public NewJFrame(String u) {
        initComponents();
        String user = u ;
        jLabel15.setText(user);
        
         if(user.equals("Doctor"))
         {
           pay.setVisible(false);
           pharmacy.setVisible(false);
           lab.setVisible(false);
           app.setVisible(false);
           emp.setVisible(false);
           sup.setVisible(false);
           assets.setVisible(false);
            patient.setVisible(false);
             pay1.setVisible(false);
           pharmacy1.setVisible(false);
           lab1.setVisible(false);
           app1.setVisible(false);
           sup1.setVisible(false);
           users.setVisible(false);
         }
         else if (user.equals("Lab Assistant"))
         {
              pay.setVisible(false);
           pharmacy.setVisible(false);
           lab.setVisible(false);
           app.setVisible(false);
           emp.setVisible(false);
           sup.setVisible(false);
           assets.setVisible(false);
            patient.setVisible(false);
             pay1.setVisible(false);
           pharmacy1.setVisible(false);
            app1.setVisible(false);
           sup1.setVisible(false);
           patient1.setVisible(false);
            users.setVisible(false);
         }
         else if (user.equals("Pharmacist"))
         {
              pay.setVisible(false);
           pharmacy.setVisible(false);
           lab.setVisible(false);
           app.setVisible(false);
           emp.setVisible(false);
           sup.setVisible(false);
           assets.setVisible(false);
           patient.setVisible(false);
           pay1.setVisible(false);
         
           app1.setVisible(false);
        
           patient1.setVisible(false);
            users.setVisible(false);
         }
         else if(user.equals("Receptionist"))
         {
            pay.setVisible(false);
           pharmacy.setVisible(false);
           lab.setVisible(false);
           app.setVisible(false);
           emp.setVisible(false);
           sup.setVisible(false);
           assets.setVisible(false);
            patient.setVisible(false); 
             users.setVisible(false);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        patient = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pay = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pharmacy = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        app = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        emp = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sup = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        assets = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        app1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        pay1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        patient1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        pharmacy1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        sup1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lab1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        users = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 31, 82));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(230, 624));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_32px.png"))); // NOI18N
        jLabel1.setText("Menu");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel11.setBackground(new java.awt.Color(0, 31, 82));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel11MousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Logout_Rounded_Up_32px_3.png"))); // NOI18N
        jLabel10.setText("LOGOUT");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 230, 30));

        patient.setBackground(new java.awt.Color(0, 31, 82));
        patient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                patientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                patientMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patientMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Physical_Therapy_32px.png"))); // NOI18N
        jLabel6.setText("Patient Handling");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout patientLayout = new javax.swing.GroupLayout(patient);
        patient.setLayout(patientLayout);
        patientLayout.setHorizontalGroup(
            patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        patientLayout.setVerticalGroup(
            patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 60));

        pay.setBackground(new java.awt.Color(0, 31, 82));
        pay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                payMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Paper_Money_32px_2.png"))); // NOI18N
        jLabel4.setText("Payments & Billing");

        javax.swing.GroupLayout payLayout = new javax.swing.GroupLayout(pay);
        pay.setLayout(payLayout);
        payLayout.setHorizontalGroup(
            payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        payLayout.setVerticalGroup(
            payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel2.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, -1));

        pharmacy.setBackground(new java.awt.Color(0, 31, 82));
        pharmacy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pharmacy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pharmacyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pharmacyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pharmacyMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Pill_32px.png"))); // NOI18N
        jLabel5.setText("Pharmacy");

        javax.swing.GroupLayout pharmacyLayout = new javax.swing.GroupLayout(pharmacy);
        pharmacy.setLayout(pharmacyLayout);
        pharmacyLayout.setHorizontalGroup(
            pharmacyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pharmacyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        pharmacyLayout.setVerticalGroup(
            pharmacyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pharmacyLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel2.add(pharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, -1));

        lab.setBackground(new java.awt.Color(0, 31, 82));
        lab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Test_Tube_32px_4.png"))); // NOI18N
        jLabel3.setText("Laboratory");

        javax.swing.GroupLayout labLayout = new javax.swing.GroupLayout(lab);
        lab.setLayout(labLayout);
        labLayout.setHorizontalGroup(
            labLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        labLayout.setVerticalGroup(
            labLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel2.add(lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, -1));

        app.setBackground(new java.awt.Color(0, 31, 82));
        app.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        app.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                appMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Timetable_32px_1.png"))); // NOI18N
        jLabel8.setText("Appointment Scheduling");

        javax.swing.GroupLayout appLayout = new javax.swing.GroupLayout(app);
        app.setLayout(appLayout);
        appLayout.setHorizontalGroup(
            appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        appLayout.setVerticalGroup(
            appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel2.add(app, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, -1));

        emp.setBackground(new java.awt.Color(0, 31, 82));
        emp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                empMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                empMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Management_32px.png"))); // NOI18N
        jLabel9.setText("Employees");

        javax.swing.GroupLayout empLayout = new javax.swing.GroupLayout(emp);
        emp.setLayout(empLayout);
        empLayout.setHorizontalGroup(
            empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        empLayout.setVerticalGroup(
            empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel2.add(emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, -1));

        sup.setBackground(new java.awt.Color(0, 31, 82));
        sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Product_32px.png"))); // NOI18N
        jLabel7.setText("Suppliers");

        javax.swing.GroupLayout supLayout = new javax.swing.GroupLayout(sup);
        sup.setLayout(supLayout);
        supLayout.setHorizontalGroup(
            supLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        supLayout.setVerticalGroup(
            supLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel2.add(sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, -1));

        assets.setBackground(new java.awt.Color(0, 31, 82));
        assets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                assetsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                assetsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                assetsMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Doctors_Bag_32px.png"))); // NOI18N
        jLabel11.setText("Assets ");

        javax.swing.GroupLayout assetsLayout = new javax.swing.GroupLayout(assets);
        assets.setLayout(assetsLayout);
        assetsLayout.setHorizontalGroup(
            assetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        assetsLayout.setVerticalGroup(
            assetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(assets, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 230, 50));

        app1.setBackground(new java.awt.Color(0, 31, 82));
        app1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        app1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                app1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                app1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                app1MousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Timetable_32px_1.png"))); // NOI18N
        jLabel21.setText("Appointment Scheduling");

        javax.swing.GroupLayout app1Layout = new javax.swing.GroupLayout(app1);
        app1.setLayout(app1Layout);
        app1Layout.setHorizontalGroup(
            app1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        app1Layout.setVerticalGroup(
            app1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(app1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, 60));

        pay1.setBackground(new java.awt.Color(0, 31, 82));
        pay1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pay1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pay1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pay1MousePressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Paper_Money_32px_2.png"))); // NOI18N
        jLabel20.setText("Payments & Billing");

        javax.swing.GroupLayout pay1Layout = new javax.swing.GroupLayout(pay1);
        pay1.setLayout(pay1Layout);
        pay1Layout.setHorizontalGroup(
            pay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pay1Layout.setVerticalGroup(
            pay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(pay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 60));

        patient1.setBackground(new java.awt.Color(0, 31, 82));
        patient1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patient1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                patient1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                patient1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patient1MousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Physical_Therapy_32px.png"))); // NOI18N
        jLabel19.setText("Patient Handling");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });

        javax.swing.GroupLayout patient1Layout = new javax.swing.GroupLayout(patient1);
        patient1.setLayout(patient1Layout);
        patient1Layout.setHorizontalGroup(
            patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        patient1Layout.setVerticalGroup(
            patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(patient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, 60));

        pharmacy1.setBackground(new java.awt.Color(0, 31, 82));
        pharmacy1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pharmacy1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pharmacy1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pharmacy1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pharmacy1MousePressed(evt);
            }
        });
        pharmacy1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Pill_32px.png"))); // NOI18N
        jLabel17.setText("Pharmacy");
        pharmacy1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, -1, -1));

        jPanel2.add(pharmacy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 70));

        sup1.setBackground(new java.awt.Color(0, 31, 82));
        sup1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sup1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sup1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sup1MousePressed(evt);
            }
        });
        sup1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Product_32px.png"))); // NOI18N
        jLabel18.setText("Suppliers");
        sup1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 11, -1, -1));

        jPanel2.add(sup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 70));

        lab1.setBackground(new java.awt.Color(0, 31, 82));
        lab1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lab1MousePressed(evt);
            }
        });
        lab1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Test_Tube_32px_4.png"))); // NOI18N
        jLabel16.setText("Laboratory");
        lab1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 11, 145, -1));

        jPanel2.add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 70));

        users.setBackground(new java.awt.Color(0, 31, 82));
        users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usersMousePressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Add_User_Male_32px.png"))); // NOI18N
        jLabel22.setText("User Creation");

        javax.swing.GroupLayout usersLayout = new javax.swing.GroupLayout(users);
        users.setLayout(usersLayout);
        usersLayout.setHorizontalGroup(
            usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        usersLayout.setVerticalGroup(
            usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 230, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, 594));

        jButton1.setBackground(new java.awt.Color(0, 31, 82));
        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_26px.png"))); // NOI18N
        jButton1.setToolTipText("minimiize window");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 30, 30));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(964, 594));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 964, 594));

        jLabel12.setFont(new java.awt.Font("Rage Italic", 1, 44)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Clinic_52px.png"))); // NOI18N
        jLabel12.setText("Deegayuu");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MEDICAL CENTER");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logged in as :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 100, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 160, 30));

        jPanel3.setBackground(new java.awt.Color(0, 31, 82));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Change my password");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 70, -1, 30));

        jButton2.setBackground(new java.awt.Color(0, 31, 82));
        jButton2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Close_Window_26px.png"))); // NOI18N
        jButton2.setToolTipText("close window");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 30, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI Symbol", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Deegayu Medical Center,No 170, Kuliyapitiya Rd, Dummalasuriya");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 400, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Symbol", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Contact No : 032 2242400");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 170, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Symbol", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Username :");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setUsername(String usn){
        jLabel26.setText(usn);
    }
    Log lo;
    public void setlogTimes(){
         lo = new Log(un);
        
    }
    private void patientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientMouseEntered
           patient.setBackground(new Color(102,153,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_patientMouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
         patient.setBackground(new Color(0,31,82));  
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void patientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientMouseClicked
      
        // TODO add your handling code here:
    }//GEN-LAST:event_patientMouseClicked

    private void patientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientMousePressed
            jDesktopPane1.removeAll();
            PatientHandling e = new PatientHandling();
            e.docNo = jLabel26.getText();
            jDesktopPane1.add(e);
             e.show();   
        // TODO add your handling code here:
    }//GEN-LAST:event_patientMousePressed

    private void payMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseEntered
         pay.setBackground(new Color(102,153,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_payMouseEntered

    private void pharmacyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacyMouseEntered
         pharmacy.setBackground(new Color(102,153,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_pharmacyMouseEntered

    private void labMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMouseEntered
          lab.setBackground(new Color(102,153,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_labMouseEntered

    private void appMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appMouseEntered
          app.setBackground(new Color(102,153,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_appMouseEntered

    private void empMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empMouseEntered
          emp.setBackground(new Color(102,153,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_empMouseEntered

    private void supMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supMouseEntered
            sup.setBackground(new Color(102,153,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_supMouseEntered

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
            jPanel11.setBackground(new Color(102,153,255));  
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
            jPanel11.setBackground(new Color(0,31,82)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11MouseExited

    private void supMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supMouseExited
             sup.setBackground(new Color(0,31,82)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_supMouseExited

    private void empMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empMouseExited
            emp.setBackground(new Color(0,31,82)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_empMouseExited

    private void appMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appMouseExited
            app.setBackground(new Color(0,31,82)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_appMouseExited

    private void labMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMouseExited
             lab.setBackground(new Color(0,31,82)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_labMouseExited

    private void pharmacyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacyMouseExited
              pharmacy.setBackground(new Color(0,31,82)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_pharmacyMouseExited

    private void payMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseExited
          pay.setBackground(new Color(0,31,82)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_payMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             this.setState(Frame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void empMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_empMouseReleased

    private void empMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empMousePressed
            jDesktopPane1.removeAll();
            employees e = new employees();
            jDesktopPane1.add(e);
             e.show();
             
        // TODO add your handling code here:
    }//GEN-LAST:event_empMousePressed

    private void assetsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assetsMouseEntered
               assets.setBackground(new Color(102,153,255));
          // TODO add your handling code here:
    }//GEN-LAST:event_assetsMouseEntered

    private void assetsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assetsMouseExited
             assets.setBackground(new Color(0,31,82)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_assetsMouseExited

    private void jPanel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MousePressed
            this.dispose();
            login l = new login();
            l.setVisible(true);
            lo.executeLog();
            
            
          // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11MousePressed

    private void supMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supMousePressed
               jDesktopPane1.removeAll();
            supl s = new supl();
            jDesktopPane1.add(s);
             s.show(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_supMousePressed

    private void labMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMousePressed
           jDesktopPane1.removeAll();
            Laboratory l = new Laboratory();
            jDesktopPane1.add(l);
             l.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_labMousePressed

    private void assetsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assetsMousePressed
            jDesktopPane1.removeAll();
            assetsManagemant m = new assetsManagemant();
            jDesktopPane1.add(m);
             m.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_assetsMousePressed

    private void pharmacyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacyMousePressed
             jDesktopPane1.removeAll();
            pharmacy m = new pharmacy();
            jDesktopPane1.add(m);
             m.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_pharmacyMousePressed

    private void appMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appMousePressed
        try {
            jDesktopPane1.removeAll();
            appointments a = new appointments();
            jDesktopPane1.add(a);
            a.show();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_appMousePressed

    private void lab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseEntered
          lab1.setBackground(new Color(102,153,255));  
       // TODO add your handling code here:
    }//GEN-LAST:event_lab1MouseEntered

    private void lab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseExited
        // TODO add your handling code here:
          lab1.setBackground(new Color(0,31,82)); 
    }//GEN-LAST:event_lab1MouseExited

    private void lab1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MousePressed
        // TODO add your handling code here:
       jDesktopPane1.removeAll();
            Laboratory l = new Laboratory();
            jDesktopPane1.add(l);
             l.show();
    }//GEN-LAST:event_lab1MousePressed

    private void pharmacy1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacy1MouseEntered
             pharmacy1.setBackground(new Color(102,153,255));         
// TODO add your handling code here:
    }//GEN-LAST:event_pharmacy1MouseEntered

    private void pharmacy1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacy1MouseExited
        // TODO add your handling code here:
          pharmacy1.setBackground(new Color(0,31,82)); 
    }//GEN-LAST:event_pharmacy1MouseExited

    private void pharmacy1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacy1MousePressed
        // TODO add your handling code here:
         jDesktopPane1.removeAll();
            pharmacy m = new pharmacy();
            jDesktopPane1.add(m);
             m.show();
    }//GEN-LAST:event_pharmacy1MousePressed

    private void sup1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup1MouseEntered
        // TODO add your handling code here:
         sup1.setBackground(new Color(102,153,255)); 
    }//GEN-LAST:event_sup1MouseEntered

    private void sup1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup1MouseExited
        // TODO add your handling code here:
          sup1.setBackground(new Color(0,31,82)); 
    }//GEN-LAST:event_sup1MouseExited

    private void sup1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup1MousePressed
        // TODO add your handling code here:
         jDesktopPane1.removeAll();
            supl s = new supl();
            jDesktopPane1.add(s);
             s.show(); 
    }//GEN-LAST:event_sup1MousePressed

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseExited

    private void patient1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_patient1MouseClicked

    private void patient1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient1MouseEntered
        // TODO add your handling code here:
         patient1.setBackground(new Color(102,153,255)); 
    }//GEN-LAST:event_patient1MouseEntered

    private void patient1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient1MousePressed
        // TODO add your handling code here:
           jDesktopPane1.removeAll();
            PatientHandling e = new PatientHandling();
            jDesktopPane1.add(e);
             e.show(); 
    }//GEN-LAST:event_patient1MousePressed

    private void pay1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pay1MouseEntered
        // TODO add your handling code here:
         pay1.setBackground(new Color(102,153,255)); 
    }//GEN-LAST:event_pay1MouseEntered

    private void pay1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pay1MouseExited
        // TODO add your handling code here:
        pay1.setBackground(new Color(0,31,82));
    }//GEN-LAST:event_pay1MouseExited

    private void app1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app1MouseEntered
        // TODO add your handling code here:
         app1.setBackground(new Color(102,153,255)); 
    }//GEN-LAST:event_app1MouseEntered

    private void app1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app1MouseExited
        // TODO add your handling code here:
        app1.setBackground(new Color(0,31,82));
    }//GEN-LAST:event_app1MouseExited

    private void app1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app1MousePressed
        try {
            // TODO add your handling code here:
            jDesktopPane1.removeAll();
            appointments a = new appointments();
            jDesktopPane1.add(a);
            a.show();
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_app1MousePressed

    private void patientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientMouseExited
            patient.setBackground(new Color(0,31,82));  
        // TODO add your handling code here:
    }//GEN-LAST:event_patientMouseExited

    private void patient1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient1MouseExited
        // TODO add your handling code here:
         patient1.setBackground(new Color(0,31,82));
    }//GEN-LAST:event_patient1MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        jLabel14.setForeground(Color.CYAN);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
         jLabel14.setForeground(Color.WHITE);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        changePassword cp = new changePassword();
        cp.user = un;
        cp.setVisible(true);
    }//GEN-LAST:event_jPanel3MousePressed

    private void usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseEntered
        // TODO add your handling code here:
         users.setBackground(new Color(102,153,255)); 
    }//GEN-LAST:event_usersMouseEntered

    private void usersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseExited
        // TODO add your handling code here:
         users.setBackground(new Color(0,31,82));
    }//GEN-LAST:event_usersMouseExited

    private void usersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMousePressed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
            userCreation u = new userCreation();
            jDesktopPane1.add(u);
             u.show();
    }//GEN-LAST:event_usersMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        lo.executeLog();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void payMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMousePressed
        // TODO add your handling code here:
       jDesktopPane1.removeAll();
           paymenthandeling p = new paymenthandeling();
            jDesktopPane1.add(p);
             p.show();
    }//GEN-LAST:event_payMousePressed

    private void pay1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pay1MousePressed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
           paymenthandeling p = new paymenthandeling();
            jDesktopPane1.add(p);
             p.show();
    }//GEN-LAST:event_pay1MousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel app;
    private javax.swing.JPanel app1;
    private javax.swing.JPanel assets;
    private javax.swing.JPanel emp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel lab;
    private javax.swing.JPanel lab1;
    private javax.swing.JPanel patient;
    private javax.swing.JPanel patient1;
    private javax.swing.JPanel pay;
    private javax.swing.JPanel pay1;
    private javax.swing.JPanel pharmacy;
    private javax.swing.JPanel pharmacy1;
    private javax.swing.JPanel sup;
    private javax.swing.JPanel sup1;
    private javax.swing.JPanel users;
    // End of variables declaration//GEN-END:variables
}
