/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpproject;

import Classes.MedicalRecord;
import Classes.Patient;
import Classes.Prescription;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class PatientHandling extends javax.swing.JInternalFrame {

    /**
     * Creates new form PatientHandling
     */
    public String docNo;
    String drugs = "";
    public PatientHandling() {
        initComponents();
        patientLoad();
        jLabel2.setVisible(false);
        jLabel5.setVisible(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jLabel20.setVisible(false);
        fillPatientID();
        fillDrugs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        contNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        bdgrp = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        dob = new com.toedter.calendar.JDateChooser();
        email = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        addr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        pid2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        height = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        allergy = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        surgHis = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        medi = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        specIss = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pName2 = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        issue = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        labTests = new javax.swing.JTextArea();
        M = new javax.swing.JCheckBox();
        E = new javax.swing.JCheckBox();
        N = new javax.swing.JCheckBox();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jButton10 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pid.setEditable(false);
        pid.setBackground(new java.awt.Color(255, 255, 255));
        pid.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel1.setText("PatientID : ");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 16))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 102, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel4.setText("Date of birth");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 102, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 102, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel7.setText("Contact Number");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel8.setText("Email");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel9.setText("Gender");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 102, -1));

        contNo.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        contNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contNoKeyTyped(evt);
            }
        });
        jPanel5.add(contNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 220, 30));

        jButton1.setBackground(new java.awt.Color(0, 31, 82));
        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Add_User_Male_32px.png"))); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, 40));

        jLabel27.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel27.setText("Blood Group");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 25));

        name.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jPanel5.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 220, 30));

        male.setBackground(new java.awt.Color(255, 255, 255));
        male.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel5.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        female.setBackground(new java.awt.Color(255, 255, 255));
        female.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel5.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        bdgrp.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        bdgrp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        bdgrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdgrpActionPerformed(evt);
            }
        });
        jPanel5.add(bdgrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 220, 30));

        jButton7.setBackground(new java.awt.Color(0, 31, 82));
        jButton7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Update_User_32px.png"))); // NOI18N
        jButton7.setText("Update");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton7MouseReleased(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 120, 40));

        jButton8.setBackground(new java.awt.Color(0, 31, 82));
        jButton8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Remove_User_Male_32px.png"))); // NOI18N
        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 120, 40));

        dob.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jPanel5.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, 30));

        email.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jPanel5.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 220, 30));

        jButton9.setBackground(new java.awt.Color(0, 31, 82));
        jButton9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Reset_32px.png"))); // NOI18N
        jButton9.setText("Reset");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, 40));

        addr.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        addr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrActionPerformed(evt);
            }
        });
        jPanel5.add(addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 220, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Please enter all the details!");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 230, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Invalid email address !");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 220, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 51, 153));
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Patient Registration", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pid2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pid2KeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel10.setText("PatientID ");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Medical Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 14))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel13.setText("Height");

        height.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        height.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heightKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel14.setText("Weight");

        weight.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        weight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weightKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel15.setText("Allergies");

        allergy.setColumns(20);
        allergy.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        allergy.setRows(5);
        jScrollPane3.setViewportView(allergy);

        surgHis.setColumns(20);
        surgHis.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        surgHis.setRows(5);
        jScrollPane4.setViewportView(surgHis);

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel16.setText("Surgical History");

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel17.setText("Special Issues");

        medi.setColumns(20);
        medi.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        medi.setRows(5);
        jScrollPane5.setViewportView(medi);

        jLabel18.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel18.setText("Medication");

        specIss.setColumns(20);
        specIss.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        specIss.setRows(5);
        jScrollPane6.setViewportView(specIss);

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel11.setText("cm");

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel12.setText("kg");

        jButton3.setBackground(new java.awt.Color(0, 31, 82));
        jButton3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Insert");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 31, 82));
        jButton4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("Please enter all the details !");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabel18)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel20)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel18))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(56, 56, 56))))
        );

        jButton2.setBackground(new java.awt.Color(0, 31, 82));
        jButton2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        error.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 51));

        jLabel19.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel19.setText("Patient Name");

        pName.setEditable(false);
        pName.setBackground(new java.awt.Color(255, 255, 255));
        pName.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel19))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pid2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jButton2)
                                .addGap(39, 39, 39)
                                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(pid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Medical Record Updation", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 13))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel22.setText("Name");

        jLabel23.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel23.setText("Age");

        pName2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        pName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pName2ActionPerformed(evt);
            }
        });

        age.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pName2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel22))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(pName2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel21.setText("Patient ID : ");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel24.setText("Issue");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, -1, -1));

        issue.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jPanel7.add(issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 11, 259, 32));

        jLabel25.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel25.setText("Drug ");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        jPanel7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 49, 127, 28));

        jLabel26.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel26.setText("Qty");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 46, -1, -1));

        jSpinner1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jPanel7.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 41, 28));

        jList1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 80));

        jButton5.setBackground(new java.awt.Color(0, 31, 82));
        jButton5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 31, 82));
        jButton6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel28.setText("Lab Tests");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, -1, -1));

        labTests.setColumns(20);
        labTests.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        labTests.setRows(5);
        jScrollPane7.setViewportView(labTests);

        jPanel7.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 205, 105));

        M.setText("M");
        jPanel7.add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 40, -1));

        E.setText("E");
        jPanel7.add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 40, -1));

        N.setText("N");
        jPanel7.add(N, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 40, -1));

        jSpinner2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jPanel7.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 114, 41, 28));

        jSpinner3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jPanel7.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 153, 41, 28));

        jLabel32.setText("TimePeriod");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 49, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        jLabel33.setText("No of Days");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel7.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 86, 39, 28));

        jButton10.setBackground(new java.awt.Color(0, 31, 82));
        jButton10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("View");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane10.setViewportView(jTextArea2);

        jLabel29.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel29.setText("Patient medical history ");

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 13)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane8.setViewportView(jTextArea3);

        jLabel30.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel30.setText("Last prescription details of the patient ");

        jButton11.setBackground(new java.awt.Color(0, 31, 82));
        jButton11.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Save Prescription");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton10))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jButton10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(64, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Prescription", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton12.setText("Full Detailed Report");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jLabel34.setText("Patient ID");

        jButton13.setText("Generate Reports");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel34)
                        .addGap(31, 31, 31)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(33, 33, 33)
                .addComponent(jButton13)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(667, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reports", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void patientLoad(){
        Patient p = new Patient();
        ResultSet rs1 = p.getDetails();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
        
    }
    void fillPatientID(){
        try{
            Connection con = DBconnect.getConnection();
            String q1 = "SELECT patientID FROM patient";
            PreparedStatement pst = con.prepareStatement(q1);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String num = rs.getString("patientID");
                jComboBox2.addItem(num);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void fillDrugs(){
        try{
            Connection con = DBconnect.getConnection();
            String q1 = "SELECT drugName FROM drugs";
            PreparedStatement pst = con.prepareStatement(q1);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String num = rs.getString("drugName");
                jComboBox1.addItem(num);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      jLabel2.setVisible(false);
      jLabel5.setVisible(false);
      String bg = bdgrp.getSelectedItem().toString();
      if(name.getText().equals("") || addr.getText().equals("") || !(male.isSelected() || female.isSelected())
              ||  contNo.getText().equals("") || dob.getDate()== null|| bg.equals("--Select--")|| email.getText().equals("")){
          getToolkit().beep();
          jLabel2.setVisible(true);
      }
      else{
         int a=0, b=0;
         for(int k =0; k<email.getText().length(); k++){
             if(email.getText().charAt(k)== '@'){
                 a=k;
             }
             else if(email.getText().charAt(k)== '.'){
                 b = k;
             }
         }
         if(b>a){
             String n = name.getText();
             String ad = addr.getText();
             String gen = "";
             if(male.isSelected())
                 gen = "male";
             else if(female.isSelected())
                 gen = "female";
             String conNo = contNo.getText();
             java.util.Date dobday = dob.getDate();
             java.sql.Date sdobday = new java.sql.Date(dobday.getTime());
             String em = email.getText();
             Patient p1 = new Patient();
             p1.addPatient(n, sdobday, ad, gen, em, bg, conNo);
             patientLoad();
             jComboBox2.removeAllItems();
             fillPatientID();
              name.setText("");
              addr.setText("");
              male.setSelected(false);
              female.setSelected(false);
              email.setText("");
              contNo.setText("");
              dob.setCalendar(null);
              bdgrp.setSelectedItem("--Select--");
         }
         else{
             getToolkit().beep();
             jLabel5.setVisible(true);
         }
      }
      
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:

       
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:

     
    }//GEN-LAST:event_femaleActionPerformed

    private void bdgrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdgrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdgrpActionPerformed

    private void jButton7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String bg = bdgrp.getSelectedItem().toString();
             String n = name.getText();
             String ad = addr.getText();
             String gen = "";
             if(male.isSelected())
                 gen = "male";
             else if(female.isSelected())
                 gen = "female";
             String conNo = contNo.getText();
             java.util.Date dobday = dob.getDate();
             java.sql.Date sdobday = new java.sql.Date(dobday.getTime());
             String em = email.getText();
             int pID = Integer.parseInt(pid.getText());
             Patient p1 = new Patient();
             p1.updatePatient(pID, n, sdobday, ad, gen, em, bg, conNo);
             patientLoad();
        
             pid.setText("");
             name.setText("");
             addr.setText("");
             male.setSelected(false);
             email.setText("");
             female.setSelected(false);
             contNo.setText("");
             dob.setCalendar(null);
             bdgrp.setSelectedItem("--Select--");
             jButton7.setEnabled(false);
             jButton8.setEnabled(false);
             jButton1.setEnabled(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         String n = name.getText();
         int pID = Integer.parseInt(pid.getText());
         Patient p2 = new Patient();
         p2.deletePatient(pID, n);
         jComboBox2.removeAllItems();
         fillPatientID();
         patientLoad();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
              pid.setText("");
              name.setText("");
              addr.setText("");
              male.setSelected(false);
              email.setText("");
              female.setSelected(false);
              contNo.setText("");
              dob.setCalendar(null);
              bdgrp.setSelectedItem("--Select--");
              jLabel2.setVisible(false);
              jLabel5.setVisible(false);
              jButton7.setEnabled(false);
              jButton8.setEnabled(false);
              jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton1.setEnabled(false);
        int selectedRowIndex = jTable1.getSelectedRow();
        name.setText(jTable1.getValueAt(selectedRowIndex, 1).toString());
        addr.setText(jTable1.getValueAt(selectedRowIndex, 5).toString());
        contNo.setText(jTable1.getValueAt(selectedRowIndex, 3).toString());
        email.setText(jTable1.getValueAt(selectedRowIndex, 6).toString());
        pid.setText(jTable1.getValueAt(selectedRowIndex, 0).toString());
        bdgrp.setSelectedItem(jTable1.getValueAt(selectedRowIndex, 7).toString());
        String g = jTable1.getValueAt(selectedRowIndex, 4).toString();
        if(g.equals("male")){
            male.setSelected(true);
            female.setSelected(false);
                   
        }
        else if(g.equals("female")){
             male.setSelected(false);
            female.setSelected(true);
        }
        try{
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date datevalue = date.parse(jTable1.getValueAt(selectedRowIndex, 2).toString());
            dob.setDate(datevalue); 
        }
        catch(Exception e){
            
        }
        /*try{

            SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd") ;
            java.util.Date datevalue = date.parse(jTable1.getValueAt(row,2).toString());
            jDateChooser1.setDate(datevalue);
        }
        catch(ParseException ex)
        {
        }*/

        /*  SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd") ;
        String date = dcn.format(jDateChooser1.getDate());
        String birth=jTable1.getValueAt(row,2);
        */
        

    }//GEN-LAST:event_jTable1MouseClicked

    private void addrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrActionPerformed

    private void contNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contNoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) ||
                c == KeyEvent.VK_DELETE )|| contNo.getText().length()> 9){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_contNoKeyTyped

    private void pid2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pid2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) ||
                c == KeyEvent.VK_DELETE )){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_pid2KeyTyped

    private void heightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) ||
                c == KeyEvent.VK_DELETE || c== '.' )){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_heightKeyTyped

    private void weightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weightKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) ||
                c == KeyEvent.VK_DELETE || c== '.' )){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_weightKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        error.setVisible(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        pName.setText("");
        height.setText("");
        weight.setText("");
        allergy.setText("");
        surgHis.setText("");
        medi.setText("");
        specIss.setText("");
        String paID = pid2.getText();
        if(paID.equals("")){
            error.setText("Please enter the patient ID!");
            error.setVisible(true);
          
        }
        else{
            Patient p3 = new Patient();
            boolean check = p3.checkPatient(Integer.parseInt(paID)); 
            
            if(check){
                ResultSet rs2 = p3.getPatientDetails(Integer.parseInt(paID));
                
                MedicalRecord mr = new MedicalRecord();
                ResultSet rs = mr.getRecord(paID);
                try{
                    if (rs2.next()){
                        pName.setText(rs2.getString("name"));
                    }
                    if(rs.next()){
                        height.setText(rs.getString("height"));
                        weight.setText(rs.getString("weight"));
                        allergy.setText(rs.getString("allergies"));
                        surgHis.setText(rs.getString("sugicalHis"));
                        medi.setText(rs.getString("medications"));
                        specIss.setText(rs.getString("specialIssues"));
                        jButton4.setEnabled(true);
                    }
                    else{
                        error.setText("New medical Record!");
                        error.setVisible(true);
                        jButton3.setEnabled(true);
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }
            else{
                error.setText("Invalid Patient ID!");
                error.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    void reset(){
         jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jLabel20.setVisible(false);
        pid2.setText("");
        pName.setText("");
        height.setText("");
        weight.setText("");
        allergy.setText("");
        surgHis.setText("");
        medi.setText("");
        specIss.setText("");
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel20.setVisible(false);
        if(height.getText().equals("") || weight.getText().equals("") || allergy.getText().equals("")
              ||  surgHis.getText().equals("") || medi.getText().equals("")|| specIss.getText().equals("")){
          getToolkit().beep();
          jLabel20.setVisible(true);
        }
        else{
            String p = pid2.getText();
            float h = Float.parseFloat(height.getText());
            float w = Float.parseFloat(weight.getText());
            String all = allergy.getText();
            String surg = surgHis.getText();
            String m = medi.getText();
            String spec = specIss.getText();
            
            MedicalRecord mr = new MedicalRecord();
            mr.addRecord(p, h, w, all, surg, m, spec);
            reset();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String pID = jComboBox2.getSelectedItem().toString();
        Patient p = new Patient();
        ResultSet rs2 = p.getPatientDetails(Integer.parseInt(pID));
        MedicalRecord mr2 = new MedicalRecord();
        ResultSet rs = mr2.getRecord(pID);
        Prescription ps = new Prescription();
        ResultSet rs3 = ps.getPrescription(pID);
        try{
            if(rs.next()){
                jTextArea2.setText("Height : "+rs.getString("height")+"cm\nWeight : "+rs.getString("weight")
                +"kg\nAllergies : "+rs.getString("allergies")+"\nSurgical History : "+rs.getString("sugicalHis")
                +"\nSpecial Issues : "+rs.getString("specialIssues")+"\nLongterm medications : "+rs.getString("medications"));
                
                
            }
            else{
                jTextArea2.setText("Sorry the medical record of this patient is not available!");
            }
            if(rs2.next()){
                pName2.setText(rs2.getString("name"));
                java.util.Date dob2 = rs2.getDate("dob");
                Date currentDate = new Date();
                LocalDate bd = rs2.getDate("dob").toLocalDate();
                Calendar now= Calendar.getInstance();
                Calendar birth = Calendar.getInstance();
                birth.setTime(dob2);
                long diff = currentDate.getTime()- dob2.getTime() ;
                long d = (1000*60*60*24*365);
                long years = Math.round(diff/d);
                int age2 = now.get(Calendar.YEAR)- birth.get(Calendar.YEAR);
                age.setText(Integer.toString(age2));
            }
            if(rs3.next()){
                jTextArea3.setText("Prescribed Date : "+rs3.getString("date")+"\nIssue : "+rs3.getString("issue")
                +"\nMedicines : "+rs3.getString("medicines")+"\nLab Tests : "+rs3.getString("labtests"));
                
                
            }
            else{
                jTextArea3.setText("This patient has no earlier precriptions!");
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void pName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pName2ActionPerformed
    DefaultListModel dm1 = new DefaultListModel();
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int qt=0;
        int mqty=0, aqty=0, nqty=0;
        ListModel model = jList1.getModel();
        boolean check =true;
        String du = jComboBox1.getSelectedItem().toString();
        int k = jComboBox1.getSelectedIndex();
        for(int i=0; i<model.getSize(); i++){
                String dr = (String) model.getElementAt(i);
                String val[] = dr.split("  ");
                String dru = val[0];
                if(du.equals(dru) || k==0){
                    check = false;
                   // break;
                }
                
         }
        if (check){
            
            if(M.isSelected()){
                mqty = Integer.parseInt(jSpinner1.getValue().toString());
                qt = qt + (Integer.parseInt(jSpinner1.getValue().toString())*Integer.parseInt(jSpinner4.getValue().toString()));
            }
            if(E.isSelected()){
                aqty = Integer.parseInt(jSpinner2.getValue().toString());
                qt = qt + (Integer.parseInt(jSpinner2.getValue().toString())*Integer.parseInt(jSpinner4.getValue().toString()));
            }
            if(N.isSelected()){
                nqty = Integer.parseInt(jSpinner3.getValue().toString());
                qt = qt + (Integer.parseInt(jSpinner3.getValue().toString())*Integer.parseInt(jSpinner4.getValue().toString()));
            }
           String treatment = jComboBox1.getSelectedItem().toString()+"  "+"M:"+Integer.toString(mqty)+"  "+"E:"+Integer.toString(aqty)+"  "+"N:"+Integer.toString(nqty)+"  "+"#days:"+jSpinner4.getValue().toString()+"  " +"tot:"+Integer.toString(qt);
           dm1.addElement(treatment);
           jList1.setModel(dm1);
        }
        else{
            getToolkit().beep();
        }
        
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dm1.removeElement(jList1.getSelectedValue());
        jList1.setModel(dm1);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        //TODO add your handling code here:
        ListModel model = jList1.getModel();
        int pNo;
        jLabel31.setText("");
         for(int i=0; i<model.getSize(); i++){
                String dr = (String) model.getElementAt(i);
                String val[] = dr.split("      ");
                String dru = val[0];
                if(drugs.equals("")){
                     drugs = dru;
                }
                else{
                     drugs = drugs +","+dru;
                 }
         }
        
        if(issue.getText().equals("") || drugs.equals("")){
            jLabel31.setText("Please enter all the details");
        }
        else{
            String pID = jComboBox2.getSelectedItem().toString();
            String iss = issue.getText();
            String labT = labTests.getText();
            java.util.Date date = new Date();
            java.sql.Date cuDate = new java.sql.Date(date.getTime());
            Prescription pr = new Prescription();
            if(labT.equals("")){
               pNo = pr.savePrescription(cuDate, iss, drugs, docNo, pID);
            }
            else{
               pNo = pr.savePrecription(cuDate, iss, drugs, docNo, labT, pID);
            }
            
            for(int i=0; i<model.getSize(); i++){
                String dr = (String) model.getElementAt(i);
                String val[] = dr.split("  ");
                String dru = val[0];
                String moqty = val[1].substring(2);
                String afqty = val[2].substring(2);
                String niqty = val[3].substring(2);
                String nodays = val[4].substring(6);
                String totqty = val[5].substring(4);
                pr.addDrugs(dru, pID, Integer.toString(pNo), Integer.parseInt(totqty),Integer.parseInt(nodays),Integer.parseInt(moqty),Integer.parseInt(afqty),Integer.parseInt(niqty));
                
            }
            pName2.setText("");
            age.setText("");
            issue.setText("");
            jList1.removeAll();
            labTests.setText("");
            jTextArea2.setText("");
            jTextArea3.setText("");
            jComboBox1.setSelectedItem("--Select--");
            jSpinner1.setValue(0);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jLabel20.setVisible(false);
        if(height.getText().equals("") || weight.getText().equals("") || allergy.getText().equals("")
              ||  surgHis.getText().equals("") || medi.getText().equals("")|| specIss.getText().equals("")){
          getToolkit().beep();
          jLabel20.setVisible(true);
        }
        else{
            String p = pid2.getText();
            float h = Float.parseFloat(height.getText());
            float w = Float.parseFloat(weight.getText());
            String all = allergy.getText();
            String surg = surgHis.getText();
            String m = medi.getText();
            String spec = specIss.getText();
            
            MedicalRecord mr = new MedicalRecord();
            mr.updateRecord(p, h, w, all, surg, m, spec);
            reset();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = DBconnect.getConnection();
            String report = "C:\\Users\\HP User\\Desktop\\itp\\ITPproject\\src\\report1pat.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp,false);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         String id = jTextField1.getText();
        HashMap param = new HashMap();
        param.put("pid",id);
        
        try{
            Connection conn = DBconnect.getConnection();
            String report = "C:\\Users\\HP User\\Desktop\\itp\\ITPproject\\src\\report2pat.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, conn);
            JasperViewer.viewReport(jp,false);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
    }//GEN-LAST:event_jButton13ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox E;
    private javax.swing.JCheckBox M;
    private javax.swing.JCheckBox N;
    private javax.swing.JTextField addr;
    private javax.swing.JTextField age;
    private javax.swing.JTextArea allergy;
    private javax.swing.JComboBox<String> bdgrp;
    private javax.swing.JTextField contNo;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JLabel error;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField height;
    private javax.swing.JTextField issue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea labTests;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextArea medi;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pName;
    private javax.swing.JTextField pName2;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pid2;
    private javax.swing.JTextArea specIss;
    private javax.swing.JTextArea surgHis;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
